
spring:
  rabbitmq:
      host: 192.168.1.112
      port: 5672
      username: rabbit
      password: 123456
      publisher-confirms: true
      virtual-host: /
      listener:
        simple:
          acknowledge-mode: manual
server:
  port: 8054

